/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/core/useGLTF';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
  };
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/3d-assets/PortraitCoin.glb') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[1.37, 0.11, 1.08]}>
        <mesh material={materials['Material.005']} geometry={nodes.Circle001.geometry} />
        <mesh material={materials['Material.002']} geometry={nodes.Circle001_1.geometry} />
        <mesh material={materials['Material.006']} geometry={nodes.Circle001_2.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload('/PortraitCoin.glb');
